# Generated by Django 3.2 on 2023-05-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_account'),
    ]

    operations = [
    ]
